// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef modelerui_h
#define modelerui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "modelerview.h"
#include <FL/Fl_Message.H>
#include <FL/Fl_Native_File_Chooser.H>
#include "dialog.h"
#include "imageio.h"
#include <iostream>
#include <fstream>
#include "camera.h"
#include "modelerdraw.h"
#include <FL/Fl_Browser.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Pack.H>
#include "modelerapp.h"

class ModelerUserInterface {
public:
  ModelerUserInterface();
  Fl_Double_Window *m_controlsWindow;
private:
  void cb_m_controlsWindow_i(Fl_Double_Window*, void*);
  static void cb_m_controlsWindow(Fl_Double_Window*, void*);
public:
  Fl_Menu_Bar *m_controlsMenuBar;
  static Fl_Menu_Item menu_m_controlsMenuBar[];
private:
  void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  void cb_Save1_i(Fl_Menu_*, void*);
  static void cb_Save1(Fl_Menu_*, void*);
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Save2_i(Fl_Menu_*, void*);
  static void cb_Save2(Fl_Menu_*, void*);
  void cb_Exit_i(Fl_Menu_*, void*);
  static void cb_Exit(Fl_Menu_*, void*);
  void cb_Normal_i(Fl_Menu_*, void*);
  static void cb_Normal(Fl_Menu_*, void*);
  void cb_Flat_i(Fl_Menu_*, void*);
  static void cb_Flat(Fl_Menu_*, void*);
  void cb_Wireframe_i(Fl_Menu_*, void*);
  static void cb_Wireframe(Fl_Menu_*, void*);
  void cb_High_i(Fl_Menu_*, void*);
  static void cb_High(Fl_Menu_*, void*);
  void cb_Medium_i(Fl_Menu_*, void*);
  static void cb_Medium(Fl_Menu_*, void*);
  void cb_Low_i(Fl_Menu_*, void*);
  static void cb_Low(Fl_Menu_*, void*);
  void cb_Poor_i(Fl_Menu_*, void*);
  static void cb_Poor(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *m_controlsAnimOnMenu;
private:
  void cb_m_controlsAnimOnMenu_i(Fl_Menu_*, void*);
  static void cb_m_controlsAnimOnMenu(Fl_Menu_*, void*);
public:
  Fl_Browser *m_controlsBrowser;
private:
  void cb_m_controlsBrowser_i(Fl_Browser*, void*);
  static void cb_m_controlsBrowser(Fl_Browser*, void*);
public:
  Fl_Scroll *m_controlsScroll;
  Fl_Pack *m_controlsPack;
  Fl_Double_Window *m_modelerWindow;
private:
  void cb_m_modelerWindow_i(Fl_Double_Window*, void*);
  static void cb_m_modelerWindow(Fl_Double_Window*, void*);
public:
  ModelerView *m_modelerView;
  void show();
private:
  const char* fileDialog(Fl_Native_File_Chooser::Type dialogType, const char* filter, const char* title=NULL);
  Fl_Native_File_Chooser* m_nativeChooser;
public:
  ~ModelerUserInterface();
};
#endif
